name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Restore google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > app/google-services.json

      - name: Check Lint rules
        run: ./gradlew ktlintCheck --configuration-cache

      - name: Build
        run: ./gradlew assembleDebug -Dorg.gradle.jvmargs="-Xmx2g" --parallel

      - name: Run unit tests for debug
        run: ./gradlew clean testDebugUnitTest --no-build-cache